use communication_layer::{ClientComLayer, ClientToUi, RecvError, SendError, UiToClient};
use futures_lite::{AsyncReadExt, AsyncWriteExt};
use game_common::*;

use std::io::ErrorKind;
use std::path::{Path, PathBuf};

use smol::fs;
use smol::net::TcpStream;

const COOKIE_EXTENSION: &str = "cookie";

/// Errors that may be generated by the client.
#[derive(Debug)]
pub enum ClientError {
    SMOLError(smol::io::Error),
    FailedToConnect,
    LostServerConnection,
    FailedToRecieveState,
    InvalidUiMessage,
    UiSendError,
    UiRecvError,
}

impl std::fmt::Display for ClientError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ClientError::SMOLError(e) => write!(f, "smol error: {}", e),
            ClientError::FailedToConnect => write!(f, "Failed connecting to server."),
            ClientError::LostServerConnection => write!(f, "Lost connection to server."),
            ClientError::FailedToRecieveState => write!(f, "Failed to recieve game state."),
            ClientError::InvalidUiMessage => write!(f, "Received unexpected message from ui."),
            ClientError::UiSendError => write!(f, "Failed to send UI message."),
            ClientError::UiRecvError => write!(f, "Failed to receive UI message."),
        }
    }
}

impl From<smol::io::Error> for ClientError {
    fn from(e: smol::io::Error) -> Self {
        match e.kind() {
            ErrorKind::ConnectionRefused => ClientError::FailedToConnect,
            ErrorKind::UnexpectedEof => ClientError::LostServerConnection,
            _ => ClientError::SMOLError(e),
        }
    }
}

impl From<SendError<ClientToUi>> for ClientError {
    fn from(_: SendError<ClientToUi>) -> Self {
        ClientError::UiSendError
    }
}

impl From<RecvError> for ClientError {
    fn from(_: RecvError) -> Self {
        ClientError::UiRecvError
    }
}

/// Infromation about the client.
pub struct GameClient {
    ip: String,
    port: String,
    com_layer: ClientComLayer,
}

/// Actions possible for [`GameClient::update_board`]
/// used to correctly handle the states of the game.
enum GameAction {
    GuessOption,
    FreezeOption,
    VictoryCheck,
    #[allow(dead_code)] // Might want to add this functionality in the future.
    RestartOption,
    NoAction,
}

impl GameClient {
    /// Genrates a new GameClient.
    ///
    /// # Arguments
    ///
    /// * `ip` - Ip address to connect to server.
    ///
    /// * `port` - Port used to connect to server.
    pub fn new(ip: &str, port: &str, com_layer: ClientComLayer) -> Self {
        Self {
            ip: String::from(ip),
            port: String::from(port),
            com_layer,
        }
    }

    /// Starts the client.
    ///
    /// # Arguments
    ///
    /// * `stall` - If true the function will
    ///   await execution of the client. Otherwise
    ///   the client will be detached.
    pub fn start(&mut self, stall: bool, username: Option<String>) -> Result<(), ClientError> {
        let ip = self.ip.clone();
        let port = self.port.clone();

        smol::block_on(async move {
            let mut com_layer = self.com_layer.clone();

            let (mut stream, cookie) = Self::setup(ip, port, username, &mut com_layer).await?;

            let mut com_layer = self.com_layer.clone();
            let client = smol::spawn(async move {
                if let Err(e) = Self::run(&mut stream, cookie, &mut com_layer).await {
                    eprintln!("Client Error: {e}");
                    com_layer.send(ClientToUi::Shutdown).await?;
                    return Err(e);
                }
                Ok(())
            });

            if stall {
                client.await?;
            } else {
                client.detach();
            }

            Ok(())
        })
    }

    async fn setup(
        ip: String,
        port: String,
        username: Option<String>,
        com_layer: &mut ClientComLayer,
    ) -> Result<(TcpStream, Cookie), ClientError> {
        let save_file_name = match username {
            Some(name) => name,
            None => Self::get_username().await?,
        };

        // Setup cookie save path
        let mut save_path = PathBuf::from("cookies");
        save_path.push(&save_file_name);
        save_path.set_extension(COOKIE_EXTENSION);

        Self::connect(ip, port, save_path.as_path(), save_file_name, com_layer).await
    }

    /// Runs the client on specified ip and port.
    async fn run(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<(), ClientError> {
        loop {
            if Self::game_wait(stream, cookie, com_layer).await? {
                break;
            }

            com_layer
                .send(communication_layer::ClientToUi::Guess)
                .await?;

            Self::game_iteration(stream, cookie, com_layer).await?;
        }

        Self::disconnect(stream, cookie).await?;

        Ok(())
    }

    async fn get_username() -> Result<String, ClientError> {
        print!("\nEnter username: ");
        flush!();

        let input = smol::unblock(|| {
            let mut line = String::new();
            std::io::stdin().read_line(&mut line)?;
            Ok::<String, std::io::Error>(line.trim().to_string())
        })
        .await?;

        Ok(input)
    }

    /// Handles connection with server on specified
    /// ip and port. This involves sending connection
    /// message to server and retreving cookie.
    ///
    /// # Returns
    ///
    /// Returns a TCPStream used for communication with
    /// server, aswell as cookie required for validating
    /// identity.
    async fn connect(
        ip: String,
        port: String,
        save_path: &Path,
        username: String,
        com_layer: &mut ClientComLayer,
    ) -> Result<(TcpStream, Cookie), ClientError> {
        println!("Client: Connecting to server at {0}:{1}\n", ip, port);

        // Setup tcp connection
        let mut stream = TcpStream::connect(format!("{0}:{1}", ip, port)).await?;

        let reconnected = Self::reconnect(&mut stream, save_path, com_layer).await?;
        let cookie;

        if let Some(c) = reconnected {
            cookie = c;
        } else {
            cookie = Self::new_connection(&mut stream, save_path, username).await?;
        }

        Self::wait_to_start(&mut stream, cookie, com_layer).await?;

        Ok((stream, cookie))
    }

    async fn wait_to_start(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<(), ClientError> {
        let mut is_session_owner = false;

        loop {
            let message = receive_message(stream).await?;

            match message {
                ToClient::SessionOwner => {
                    is_session_owner = true;
                    let temp_stream = stream.clone();
                    smol::spawn(async move {
                        if let Err(e) = Self::session_owner(&mut temp_stream.clone(), cookie).await
                        {
                            eprintln!("Session Owner Error: {}", e);
                        }
                    })
                    .detach();
                }

                ToClient::PlayerList(player_list) => {
                    Self::update_lobby_screen(player_list, is_session_owner).await;
                }

                ToClient::StartSession => {
                    println!("Connection established with cookie: {}", cookie);

                    send_message(stream, ToServer::StartGame(cookie)).await?;

                    if let ToClient::State(state) = receive_message(stream).await? {
                        com_layer
                            .send(communication_layer::ClientToUi::Start(
                                state.game.get_first_event().year,
                            ))
                            .await?;
                    } else {
                        return Err(ClientError::InvalidUiMessage);
                    }

                    return Ok(());
                }

                ToClient::RejoinSession => return Ok(()),

                invalid => println!("Invalid message: {:?}", invalid),
            }
        }
    }

    async fn update_lobby_screen(player_list: Vec<String>, is_session_owner: bool) {
        clear!();

        println!("\n~~~~~ Player List ~~~~~");
        for player in player_list {
            println!("Player: {}", player);
        }
        println!("~~~~~~~~~~~~~~~~~~~~~~~");

        if is_session_owner {
            println!("\nYou are the ession owner.");
            println!("Press enter to start the game: ");
        }
    }

    async fn session_owner(stream: &mut TcpStream, cookie: Cookie) -> Result<(), ClientError> {
        use std::io::Read;

        smol::unblock(|| std::io::stdin().read_exact(&mut [0u8])).await?;

        send_message(stream, ToServer::StartSession(cookie)).await?;
        Ok(())
    }

    /// Tries to reconnect client to the server.
    /// If it succeeds the cookie will be returned,
    /// otherwise none. However if any message with
    /// the server fails an error will be returned.
    async fn reconnect(
        stream: &mut TcpStream,
        save_path: &Path,
        com_layer: &mut ClientComLayer,
    ) -> Result<Option<Cookie>, ClientError> {
        let cookie = Self::load_cookie(save_path).await?;

        if let Some(c) = cookie {
            send_message(stream, ToServer::Reconnect(c)).await?;

            let message = receive_message(stream).await?;

            if let ToClient::ReconnectAccepted(state) = message {
                com_layer
                    .send(ClientToUi::SetBoard(state.game.clone()))
                    .await?;
                return Ok(Some(c));
            }
        }

        Ok(None)
    }

    /// Send [`ToServer::Connect`] message to server,
    /// and registers recieved cookie. The cookie is
    /// also saved to file.
    async fn new_connection(
        stream: &mut TcpStream,
        save_path: &Path,
        username: String,
    ) -> Result<Cookie, ClientError> {
        send_message(stream, ToServer::Connect(username)).await?;

        let message = receive_message(stream).await?;

        if let ToClient::ConnectionAccepted(cookie) = message {
            Self::remove_cookie(save_path).await?;
            Self::save_cookie(save_path, cookie).await?;
            return Ok(cookie);
        }

        Err(ClientError::FailedToConnect)
    }

    async fn remove_cookie(path: &Path) -> Result<(), ClientError> {
        match fs::remove_file(path).await {
            Ok(_) => Ok(()),
            Err(e) if e.kind() == smol::io::ErrorKind::NotFound => Ok(()),
            Err(e) => Err(ClientError::SMOLError(e)),
        }
    }

    /// Save cookie to file. If file or path does
    /// not exist, it will be created.
    async fn save_cookie(path: &Path, cookie: Cookie) -> Result<(), ClientError> {
        let mut temp_path = PathBuf::from(path);
        temp_path.set_extension(COOKIE_EXTENSION);

        let mut file = fs::File::create(&temp_path).await?;

        file.write_all(cookie.to_string().as_bytes()).await?;

        // Ensure data is written to file
        file.flush().await?;

        // Make sure file is closed
        drop(file);

        // Replace temp file (This is an atomic operation)
        fs::rename(&temp_path, path).await?;

        Ok(())
    }

    /// Loads cookie from specified file.
    ///
    /// # Returns
    ///
    /// If file is found it will be parsed and
    /// the value will be returned. If the files
    /// does not exist [`None`] will be returned.
    /// Otherwise a [`ClientError`] will be returned.
    async fn load_cookie(path: &Path) -> Result<Option<Cookie>, ClientError> {
        let mut file = match fs::File::open(path).await {
            Ok(f) => f,
            Err(e) if e.kind() == smol::io::ErrorKind::NotFound => return Ok(None),
            Err(e) => return Err(ClientError::SMOLError(e)),
        };

        let mut content = String::new();
        file.read_to_string(&mut content).await?;

        let cookie = content.trim().parse::<Cookie>().map_err(|e| {
            ClientError::SMOLError(smol::io::Error::new(smol::io::ErrorKind::InvalidData, e))
        })?;

        Ok(Some(cookie))
    }

    async fn game_wait(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<bool, ClientError> {
        loop {
            println!("Waiting for other player(s) ...");
            com_layer.send(ClientToUi::Wait).await?;

            let message = receive_message(stream).await?;

            match message {
                ToClient::StartIteration => return Ok(false),
                ToClient::GameOver(name) => {
                    com_layer.send(ClientToUi::Victory(name.clone())).await?;
                    println!("Player: {} won!", name);
                    send_message(stream, ToServer::Disconnect(cookie)).await?;
                    return Ok(true);
                }

                invalid => println!("Invalid message white waiting. Message: {:?}", invalid),
            }
        }
    }

    /// Runs one iteration of the chronology game.
    /// This involves handling user guess, checking
    /// for victory and handling user input for
    /// freezing.
    ///
    /// # Returns
    ///
    /// If victory is achieved, true will be returned
    /// otherwise false.
    async fn game_iteration(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<(), ClientError> {
        // Handle user guess
        Self::update_board(stream, cookie, GameAction::GuessOption, com_layer).await?;

        // Check for victory
        let victory =
            Self::update_board(stream, cookie, GameAction::VictoryCheck, com_layer).await?;

        // Handle user freeze option
        if !victory {
            let freeze =
                Self::update_board(stream, cookie, GameAction::FreezeOption, com_layer).await?;
            if freeze {
                Self::update_board(stream, cookie, GameAction::NoAction, com_layer).await?;
            }
        }

        // Restart iteration
        send_message(stream, ToServer::RestartIteration(cookie)).await?;

        Ok(())
    }

    /// Updates the board by requesting the state
    /// from the server and then manipulating it
    /// by specifying a `action`.
    async fn update_board(
        stream: &mut TcpStream,
        cookie: Cookie,
        action: GameAction,
        com_layer: &mut ClientComLayer,
    ) -> Result<bool, ClientError> {
        send_message(stream, ToServer::RequestState(cookie)).await?;

        let message = receive_message(stream).await?;

        if let ToClient::State(ref state) = message {
            match action {
                GameAction::GuessOption => {
                    //state.game.display_board(true);
                    Self::gues_option(stream, cookie, state, com_layer).await?
                }
                GameAction::FreezeOption => {
                    let correct = state.game.was_last_correct();
                    //state.game.display_board(correct);

                    let mut year = None;
                    if correct {
                        if let Some(last_event) = state.game.last_correct_event() {
                            year = Some(last_event.year);
                        }
                    } else if let Some(incorrect_event) = state.incorrect_event.clone() {
                        year = Some(incorrect_event.year);
                    }

                    if let Some(year) = year {
                        com_layer
                            .send(communication_layer::ClientToUi::Result(correct, year))
                            .await?;
                    } else {
                        println!("Something went wrong");
                    }

                    if correct {
                        return Self::freeze_option(stream, cookie, com_layer).await;
                    } else {
                        Self::incorrect_action(stream, cookie, com_layer).await?;
                    }
                }
                GameAction::VictoryCheck => {
                    return Self::victory_check(stream, cookie).await;
                }
                GameAction::RestartOption => {
                    return Self::restart_option(stream, cookie, state).await;
                }
                GameAction::NoAction => {}
            }
        } else {
            return Err(ClientError::FailedToRecieveState);
        }

        Ok(false)
    }

    /// Geta the guess provided by the user and
    /// sends it to the server.
    async fn gues_option(
        stream: &mut TcpStream,
        cookie: Cookie,
        state: &GameState,
        com_layer: &mut ClientComLayer,
    ) -> Result<(), ClientError> {
        if let Some(event) = &state.current_event {
            com_layer.send(ClientToUi::SetEvent(event.clone())).await?;
        }

        //let guess = state.game.user_guess().await;
        if let UiToClient::Guess(guess) = com_layer.receive().await? {
            send_message(stream, ToServer::Guess(cookie, guess)).await?;
        } else {
            return Err(ClientError::InvalidUiMessage);
        }

        Ok(())
    }

    /// Gets a boolean from the [`GameState`]
    /// representing wheter the user wants
    /// to freeze the board or not. The result
    /// is sent to the server.
    async fn freeze_option(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<bool, ClientError> {
        com_layer.send(ClientToUi::AskFreeze).await?;

        if let UiToClient::Freeze(value) = com_layer.receive().await? {
            send_message(stream, ToServer::Freeze(cookie, value)).await?;
            return Ok(value);
        }
        Err(ClientError::InvalidUiMessage)
    }

    /// Checks if current event was incorrect and
    /// if so asks user for action, and then sends
    /// a [`ToServer::IncorrectGuess`] message to
    /// the server.
    async fn incorrect_action(
        stream: &mut TcpStream,
        cookie: Cookie,
        com_layer: &mut ClientComLayer,
    ) -> Result<(), ClientError> {
        send_message(stream, ToServer::IncorrectGuess(cookie)).await?;

        if let UiToClient::Continue = com_layer.receive().await? {
            return Ok(());
        }
        Err(ClientError::InvalidUiMessage)
    }

    /// Requests a victory check from the server
    /// and returns true if victory has been
    /// achieved, otherwise returns false.
    async fn victory_check(stream: &mut TcpStream, cookie: Cookie) -> Result<bool, ClientError> {
        send_message(stream, ToServer::RequestVictory(cookie)).await?;

        let message: ToClient = receive_message(stream).await?;

        if let ToClient::VictoryResult(result) = message {
            if result {
                return Ok(true);
            }
        } else {
            return Err(ClientError::FailedToRecieveState);
        }
        Ok(false)
    }

    /// Gets option whether the user wants to
    /// restart the game or not. If the user
    /// wants to restart a [`ToServer::RestartGame`]
    /// message will be sent to the server.
    async fn restart_option(
        stream: &mut TcpStream,
        cookie: Cookie,
        state: &GameState,
    ) -> Result<bool, ClientError> {
        let option = state.game.user_restart_option().await;

        if option {
            send_message(stream, ToServer::RestartGame(cookie)).await?;
        }

        Ok(option)
    }

    /// Sends a [`ToServer::Disconnect`] message
    /// to the server.
    async fn disconnect(stream: &mut TcpStream, cookie: Cookie) -> Result<(), ClientError> {
        send_message(stream, ToServer::Disconnect(cookie)).await?;

        Ok(())
    }
}
